name             'deploy-user'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures deploy-user'
long_description 'Installs/Configures deploy-user'
version          '0.1.0'
